import { ResumeData } from '../types/resume';

export const sampleResumeData: ResumeData = {
  personalInfo: {
    firstName: 'Alex',
    lastName: 'Johnson',
    email: 'alex.johnson@email.com',
    phone: '+1 (555) 123-4567',
    linkedin: 'linkedin.com/in/alexjohnson',
    github: 'github.com/alexjohnson',
    address: 'San Francisco, CA',
    title: 'Senior Software Engineer',
    website: 'alexjohnson.dev',
    portfolio: '',
    twitter: '',
    photo: '',
    showPhoto: false,
    photoShape: 'circle',
    photoSize: 'medium',
  },
  summary:
    'Passionate software engineer with 6+ years of experience building scalable web applications. Expert in React, TypeScript, and Node.js with a strong focus on clean architecture and user experience. Led cross-functional teams to deliver high-impact products serving millions of users.',
  education: [
    {
      id: '1',
      institution: 'Stanford University',
      degree: 'Master of Science',
      fieldOfStudy: 'Computer Science',
      startDate: '2015-09',
      endDate: '2017-06',
      gpa: '3.9',
      description: 'Specialized in Machine Learning and Distributed Systems',
    },
    {
      id: '2',
      institution: 'UC Berkeley',
      degree: 'Bachelor of Science',
      fieldOfStudy: 'Computer Science',
      startDate: '2011-09',
      endDate: '2015-05',
      gpa: '3.7',
    },
  ],
  experience: [
    {
      id: '1',
      company: 'TechCorp Inc.',
      position: 'Senior Software Engineer',
      startDate: '2021-03',
      endDate: '',
      current: true,
      description:
        '• Led development of a real-time analytics platform processing 10M+ events daily\n• Architected microservices infrastructure reducing deployment time by 60%\n• Mentored team of 5 junior engineers, improving code review quality by 40%\n• Implemented CI/CD pipelines reducing production incidents by 35%',
      location: 'San Francisco, CA',
    },
    {
      id: '2',
      company: 'StartupXYZ',
      position: 'Software Engineer',
      startDate: '2018-06',
      endDate: '2021-02',
      current: false,
      description:
        '• Built customer-facing dashboard used by 50,000+ daily active users\n• Reduced page load time by 45% through performance optimization\n• Developed RESTful APIs handling 100k+ requests per minute\n• Collaborated with product team to define technical requirements',
      location: 'Palo Alto, CA',
    },
    {
      id: '3',
      company: 'InnovateTech',
      position: 'Junior Developer',
      startDate: '2017-07',
      endDate: '2018-05',
      current: false,
      description:
        '• Developed and maintained web applications using React and Node.js\n• Participated in agile development processes and daily standups\n• Fixed 150+ bugs and implemented 30+ feature requests',
      location: 'Mountain View, CA',
    },
  ],
  skills: [
    { id: '1', name: 'React', level: 'Expert', category: 'Technical' },
    { id: '2', name: 'TypeScript', level: 'Expert', category: 'Technical' },
    { id: '3', name: 'Node.js', level: 'Advanced', category: 'Technical' },
    { id: '4', name: 'Python', level: 'Advanced', category: 'Technical' },
    { id: '5', name: 'AWS', level: 'Advanced', category: 'Technical' },
    { id: '6', name: 'PostgreSQL', level: 'Advanced', category: 'Technical' },
    { id: '7', name: 'Docker', level: 'Intermediate', category: 'Technical' },
    { id: '8', name: 'GraphQL', level: 'Advanced', category: 'Technical' },
    { id: '9', name: 'Team Leadership', level: 'Advanced', category: 'Soft' },
    { id: '10', name: 'Agile/Scrum', level: 'Expert', category: 'Soft' },
  ],
  projects: [
    {
      id: '1',
      name: 'E-Commerce Platform',
      description:
        'Built a full-stack e-commerce platform with real-time inventory management, payment processing, and order tracking. Handles 10,000+ daily transactions.',
      technologies: ['React', 'Node.js', 'PostgreSQL', 'Stripe', 'Redis'],
      link: 'ecommerce-demo.com',
      github: 'github.com/alexjohnson/ecommerce',
      startDate: '2022-01',
      endDate: '2022-06',
    },
    {
      id: '2',
      name: 'AI Chat Assistant',
      description:
        'Developed an AI-powered chat assistant using OpenAI GPT models with custom training for customer support automation.',
      technologies: ['Python', 'FastAPI', 'React', 'OpenAI', 'MongoDB'],
      link: 'ai-chat-demo.com',
      github: '',
      startDate: '2023-03',
      endDate: '2023-08',
    },
  ],
  certifications: [
    {
      id: '1',
      name: 'AWS Solutions Architect Professional',
      issuer: 'Amazon Web Services',
      date: '2023-01',
      expiryDate: '2026-01',
      credentialId: 'AWS-SAP-123456',
      link: 'aws.amazon.com/verification',
    },
    {
      id: '2',
      name: 'Google Cloud Professional Developer',
      issuer: 'Google',
      date: '2022-06',
      credentialId: 'GCP-PD-789012',
    },
  ],
  languages: [
    { id: '1', name: 'English', proficiency: 'Native' },
    { id: '2', name: 'Spanish', proficiency: 'Advanced' },
    { id: '3', name: 'Mandarin', proficiency: 'Elementary' },
  ],
  interests: [
    { id: '1', name: 'Open Source Contributing' },
    { id: '2', name: 'Tech Blogging' },
    { id: '3', name: 'Mountain Biking' },
    { id: '4', name: 'Photography' },
  ],
  awards: [
    {
      id: '1',
      title: 'Innovation Award',
      issuer: 'TechCorp Inc.',
      date: '2023-06',
      description: 'Recognized for developing patent-pending algorithm improving system efficiency by 40%',
    },
    {
      id: '2',
      title: 'Hackathon Winner',
      issuer: 'HackSF 2022',
      date: '2022-09',
      description: 'First place for AI-powered accessibility tool',
    },
  ],
  publications: [
    {
      id: '1',
      title: 'Scalable Microservices Architecture Patterns',
      publisher: 'IEEE Software',
      date: '2023-03',
      link: 'ieee.org/publication/123',
      authors: 'Alex Johnson, Jane Doe',
    },
  ],
  volunteer: [
    {
      id: '1',
      organization: 'Code.org',
      role: 'Volunteer Instructor',
      startDate: '2020-01',
      endDate: '',
      current: true,
      description: 'Teaching coding fundamentals to underrepresented high school students. Led 20+ workshops reaching 200+ students.',
    },
  ],
  references: [
    {
      id: '1',
      name: 'Sarah Chen',
      title: 'Engineering Director',
      company: 'TechCorp Inc.',
      email: 'sarah.chen@techcorp.com',
      phone: '+1 (555) 987-6543',
      relationship: 'Current Manager',
    },
  ],
  customSections: [],
  sectionVisibility: {
    summary: true,
    experience: true,
    education: true,
    skills: true,
    projects: true,
    certifications: true,
    languages: true,
    interests: true,
    awards: true,
    publications: true,
    volunteer: true,
    references: true,
    customSections: true,
  },
  sectionOrder: [
    'summary',
    'experience',
    'education',
    'skills',
    'projects',
    'certifications',
    'awards',
    'publications',
    'volunteer',
    'languages',
    'interests',
    'references',
    'customSections',
  ],
};

export const getEmptyResumeData = (): ResumeData => ({
  personalInfo: {
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    linkedin: '',
    github: '',
    address: '',
    title: '',
    website: '',
    portfolio: '',
    twitter: '',
    photo: '',
    showPhoto: false,
    photoShape: 'circle',
    photoSize: 'medium',
  },
  summary: '',
  education: [],
  experience: [],
  skills: [],
  projects: [],
  certifications: [],
  languages: [],
  interests: [],
  awards: [],
  publications: [],
  volunteer: [],
  references: [],
  customSections: [],
  sectionVisibility: {
    summary: true,
    experience: true,
    education: true,
    skills: true,
    projects: true,
    certifications: true,
    languages: true,
    interests: true,
    awards: true,
    publications: true,
    volunteer: true,
    references: true,
    customSections: true,
  },
  sectionOrder: [
    'summary',
    'experience',
    'education',
    'skills',
    'projects',
    'certifications',
    'awards',
    'publications',
    'volunteer',
    'languages',
    'interests',
    'references',
    'customSections',
  ],
});
